---
- name: Validate sshd config
  command: sshd -t
  changed_when: false
  listen: restart sshd

- name: Restart sshd
  shell: "sleep 1 && systemctl restart {{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
  async: 10
  poll: 0
  listen: restart sshd
