---
- name: Validate sshd config
  command: sshd -t
  changed_when: false
  listen: restart sshd

- name: Restart sshd
  systemd:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted
  listen: restart sshd
